<?php
// 登録単位にデータ配列を["table_name"=>[],"table_name"=>[]]と用意する。登録単位でループしてシーダーは登録する
// php artisan db:seed --class=CustSeeder
return [
    [
        "flg"=>"Y",
        "webmem"=>"Y",
        "login_pass"=>"password",
        "res_permit_cnt"=>0,
        "gmo_credit"=>"abcdefg1234567890",
        "memberid"=>1,
        "memberid2"=>"1",
        "reason_admit"=>0,
        "admit_date"=>"2019-06-10",
        "admit_onday"=>0,
        "reason_rest"=>0,
        "rest_date"=>"2019-06-10",
        "quit"=>0,
        "quit_date"=>"2019-06-10",
        "readmit_date"=>"2019-06-10",
        "resumption"=>"2019-06-10",
        "recess"=>"2019-06-10",
        "idm"=>"",
        "rank"=>"Z",
        "memtype"=>1,
        "experience_flg"=>0,
        "store_id"=>1,
        "last_tenpo"=>1,
        "sex"=>"1",
        "kana"=>"テスト",
        "name"=>"テスト",
        "nickname"=>"テスト",
        "caution"=>"",
        "b_code"=>"",
        "b_name"=>"",
        "br_code"=>"",
        "br_name"=>"",
        "c_code"=>"",
        "c_name"=>"",
        "a_name"=>"",
        "a_number"=>"",
        "y_code"=>"",
        "y_number"=>"",
        "ya_name"=>"",
        "bank_type"=>1,
        "transfer_date"=>null,
        "b_year"=>2000,
        "b_month"=>1,
        "b_day"=>11,
        "kubun1_id"=>0,
        "kubun2_id"=>0,
        "kubun3_id"=>0,
        "kubun4_id"=>0,
        "kubun5"=>"0",
        "kubun6"=>"0",
        "kubun7"=>"0",
        "kubun8"=>"0",
        "hw"=>"1",
        "h_zip"=>"108-0073",
        "h_addr1"=>"東京都港区三田",
        "h_addr2"=>"99-9-9",
        "h_buil"=>"テストビル4F",
        "ng_h_hagaki"=>"",
        "h_tel1"=>"",
        "h_tel2"=>"",
        "h_tel3"=>"",
        "cellph1"=>"",
        "cellph2"=>"",
        "cellph3"=>"",
        "fax1"=>"",
        "fax2"=>"",
        "fax3"=>"",
        "c_mail"=>"nuzigepyo@eay.jp",
        "c_conf"=>1,
        "ng_c_mail"=>0,
        "pc_mail"=>"hobyo53@neko2.net",
        "pc_conf"=>1,
        "ng_pc_mail"=>0,
        "job_id"=>1,
        "jobkind_id"=>null,
        "syoujo_sub1"=>"",
        "syoujo_sub2"=>"",
        "t_change"=>"",
        "t_comment"=>"",
        "kana_g"=>"保護者氏名",
        "name_g"=>"ホゴシャシメイ",
        "fam_relation"=>"父",
        "h_zip_g"=>"",
        "h_addr1_g"=>"",
        "h_addr2_g"=>"",
        "h_buil_g"=>"",
        "ng_h_hagaki_g"=>"",
        "h_tel1_g"=>"",
        "h_tel2_g"=>"",
        "h_tel3_g"=>"",
        "cellph1_g"=>"",
        "cellph2_g"=>"",
        "cellph3_g"=>"",
        "fax1_g"=>"",
        "fax2_g"=>"",
        "fax3_g"=>"",
        "c_mail_g"=>"",
        "pc_mail_g"=>"",
        "memberflg"=>"N",
        "type_edit_date"=>null,
        "dm_list"=>"1,2",
        "w_report"=>"",
        "m_pub"=>0,
        "wpatern"=>0,
        "week_id"=>"0",
        "first_buy"=>null,
        "first_lesson"=>null,
        "last_lesson"=>null,
        "eraser_name"=>"",
        "reg_user"=>"999",
        "edit_tenpoid"=>0,
        "edit_date"=>null,
        "edit_time"=>"",
        "del_date"=>null,
        "del_time"=>"",
        "raiten"=>null,
        "reedit_date"=>null,
        "unpay_total"=>null,
        "mov_id"=>"",
        "mov_id_all"=>"",
        "info_boad"=>"",
        "mail_delivery"=>"",
        "no_mess"=>0,
        "reserve_lock"=>"N",
        "salt"=>"abcdefg1234567890",
        "password_change_datetime"=>"2019-06-10 16:02:43.563",
        "login_trial_count"=>0,
        "assign" => [
            // ピボットテーブル系の情報はここで作る
            "tenpo_name" => [
                "銀座 1st(GNZ 1st)",
                "自由が丘(JYO)"
            ],
            // 関連テーブル系の情報はここで作る
            "cust_memtype_name" => "マンスリーメンバー",
            "schedule" => [
                "sc_soid"   => 0,    // 売り上げID（shop_order.id）
                "sc_flg"    => 1,    // 1:スケジュール実行前 （変更予約は1を対象？）
                "appli_flg" => 0,               // 0： マンスリー種別／所属店変更／継続課金 application.apid
                //"sc_cid"    => ,              // cust_master.cid シーダーで紐づけ
                "sc_date"   => date("Y-m-d"),   // スケジュール実行日（NOTNULLだけど、sc_flg=1の場合何の日付？）
                //"sc_memtype"=> ,   // 変更先会員種別ID：シーダーで自種別以外を割当
                //"sc_tenpo"=> ,     // 変更先店舗ID：シーダーで自所属店舗以外を割当
                "sc_regdate" => date('Y-m-d')
            ],
        ],
    ],
    //
];